name: flutter_day_seoul
description: A Flutter Desktop Embedded Slide For presentation.
authors:
  - Dreamwalker <aristojeff@gmail.com>

homepage: "https://github.com/JAICHANGPARK/flutter_day_extended_seoul_2020"
repository:  "https://github.com/JAICHANGPARK/flutter_day_extended_seoul_2020"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  google_fonts: ^1.1.0
  markdown: ^2.1.5
  flutter_markdown: ^0.4.2
  decoding_text_effect: ^1.1.1
  flutter_particles: ^1.0.0+7

  flutter_svg: ^0.18.0
  cached_network_image: ^2.2.0+1
  animated_text_kit: ^2.2.0
  geopattern_flutter: ^0.1.1

  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/final/
